[workspace]

members = [
    "pallas-codec",
    "pallas-addresses",
    "pallas-multiplexer",
    "pallas-miniprotocols",
    "pallas-crypto",
    "pallas-primitives",
    "pallas-traverse",
    "pallas",
    "unstable/pallas-json-ld",
    "examples/block-download",
    "examples/block-decode",
    "examples/n2n-miniprotocols",
    "examples/n2c-miniprotocols",
]
