[workspace]

members = [
    "pallas-applying",
    "pallas-codec",
    "pallas-addresses",
    "pallas-network",
    "pallas-crypto",
    "pallas-configs",
    "pallas-primitives",
    "pallas-traverse",
    "pallas-utxorpc",
    "pallas",
    "examples/block-download",
    "examples/block-decode",
    "examples/n2n-miniprotocols",
    "examples/n2c-miniprotocols",
]
