[package]
name = "pallas-wallet"
description = "Cardano wallet utilities such as key generation"
version = "0.20.0"
edition = "2021"
repository = "https://github.com/txpipe/pallas"
homepage = "https://github.com/txpipe/pallas"
license = "Apache-2.0"
readme = "README.md"
authors = ["Santiago Carmuega <santiago@carmuega.me>"]

[dependencies]
thiserror = "1.0.49"
pallas-crypto = { version = "=0.20.0", path = "../pallas-crypto" }
ed25519-bip32 = "0.4.1"
rand = "0.8.5"
bip39 = { version = "2.0.0", features = ["rand_core"] }
cryptoxide = "0.4.4"
bech32 = "0.9.1"
