[package]
name = "pallas-network2"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
futures = "0.3.31"
trait-variant = "0.1.2"
rand = { version = "0.9.1", optional = true }
tokio = { version = "1.45.1", optional = true, features = ["full"] }
pallas-codec = { path = "../pallas-codec" }
chrono = "0.4.41"
opentelemetry = "0.30.0"
tracing = "0.1.41"
byteorder = "1.5.0"
socket2 = "0.6.0"
thiserror = "2.0.16"
hex = "0.4.3"

[features]
emulation = ["tokio", "rand"]
default = ["emulation"]
blueprint = []

[dev-dependencies]
