[package]
name = "pallas-hardano"
description = "Pallas interoperability with the Haskel Cardano node implementation"
version = "0.30.2"
edition = "2021"
repository = "https://github.com/txpipe/pallas"
homepage = "https://github.com/txpipe/pallas"
documentation = "https://docs.rs/pallas-hardano"
license = "Apache-2.0"
readme = "README.md"
authors = ["Santiago Carmuega <santiago@carmuega.me>"]

[dependencies]
thiserror = "1.0.49"
binary-layout = "3.2.0"
tap = "1.0.1"
tracing = "0.1.40"
pallas-traverse = { version = "=0.30.2", path = "../pallas-traverse" }
pallas-network = { version = "=0.30.2", path = "../pallas-network" }

[dev-dependencies]
tracing-subscriber = "0.3.17"
hex = "0.4.3"
