[package]
name = "p2p-responder"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pallas-network2 = { path = "../../pallas-network2" }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "time"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "registry", "std", "fmt"] }
opentelemetry = { version = "0.30.0", features = ["trace", "metrics", "logs"] }
opentelemetry_sdk = { version = "0.30.0", features = ["trace", "metrics", "logs"] }
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic", "trace", "metrics", "logs", "internal-logs"] }
opentelemetry-appender-tracing = "0.30.1"
