[package]
name = "pallas-miniprotocols"
description = "Implementation of the Ouroboros network mini-protocols state-machines"
version = "0.5.4"
edition = "2021"
repository = "https://github.com/txpipe/pallas"
homepage = "https://github.com/txpipe/pallas"
documentation = "https://docs.rs/pallas-machines"
license = "Apache-2.0"
readme = "README.md"
authors = [
    "Santiago Carmuega <santiago@carmuega.me>"
]

[dependencies]
pallas-multiplexer = { version = "0.5.0",  path = "../pallas-multiplexer/" }
minicbor = { version="0.14", features=["half", "std"] }
log = "0.4.14"
hex = "0.4.3"
itertools = "0.10.3"
net2 = "0.2.37"

[dev-dependencies]
env_logger = "0.9.0"
pallas-primitives = { version = "0.5.0",  path = "../pallas-primitives/" }
