[package]
name = "p2p-discovery"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallas-network2 = { path = "../../pallas-network2" }
pallas-primitives = { path = "../../pallas-primitives" }
pallas-traverse = { path = "../../pallas-traverse" }
pallas-codec = { path = "../../pallas-codec" }
pallas-crypto = { path = "../../pallas-crypto" }
hex = "0.4.3"
thiserror = "1.0.31"
rand = "0.8"

tokio = { version = "1.27.0", features = ["rt-multi-thread", "tracing"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
opentelemetry = { version = "0.30.0", features = ["trace", "metrics", "logs"] }
opentelemetry_sdk = { version = "0.30.0", features = ["trace", "metrics", "logs"] }
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic", "trace", "metrics", "logs", "internal-logs"] }
opentelemetry-appender-tracing = "0.30.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "registry", "std", "fmt"] }
anyhow = "1.0.99"
